### ISSUE TITLE
Usable for detecting Bonjour devices?

### ISSUE THREAD

**Issue by caspahouzer** [hoyo/TiMultipeer#1]
Hello,

can I use this module to find all Bonjour devices in the network?

**Comment by hoyo** [comment]
Maybe not, unfortunately.
The multipeer connectivity is different from Bonjour.

**Comment by caspahouzer** [comment]
Thanks. 

Would you be able to build a Bonjour module?
The appcelerator api is absolutely incomplete 
- Sebastian 

Sent from my iPhone

**Comment by hoyo** [comment]
How about if you extend official api?
Following module may be relevant to you.
https://github.com/ryugoo/TiExtendWeb
